# Generated by Django 4.1.5 on 2023-02-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0002_subscriberscat_category_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='can_create_post',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_in',
            field=models.DateField(auto_now_add=True),
        ),
    ]
