# Generated by Django 4.1.5 on 2023-02-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0004_alter_post_time_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='can_create_post',
        ),
        migrations.AddField(
            model_name='post',
            name='post_opportunity',
            field=models.CharField(default='True', max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_in',
            field=models.DateField(auto_now_add=True),
        ),
    ]
