# Generated by Django 4.1.5 on 2023-02-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0005_remove_author_can_create_post_post_post_opportunity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='can_create_post',
            field=models.CharField(default='True', max_length=5),
        ),
    ]
