# Generated by Django 4.1.5 on 2023-02-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0006_author_can_create_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='can_create_post',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
