# Generated by Django 4.1.5 on 2023-02-27 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0007_alter_author_can_create_post_alter_post_time_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_opportunity',
        ),
    ]
