# Generated by Django 4.1.5 on 2023-02-27 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0008_remove_post_post_opportunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_in',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
