# Generated by Django 4.1.5 on 2023-02-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0010_alter_author_can_create_post_alter_post_time_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='can_create_post',
            field=models.CharField(max_length=5),
        ),
    ]
