# Generated by Django 4.1.5 on 2023-02-27 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0011_alter_author_can_create_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='can_create_post',
        ),
    ]
